### ISSUE TITLE
Take advantage of using the .settings.json for custom themes and auto authentication

### ISSUE THREAD

**Issue by tterb** [tjhrulz/GPMDP-Plugin#4]
I'm not sure if you're already aware of this, but I believe that custom theme colors are still provided in the *.settings.json* file under the "themeColor" parameter.
Like I said, I'm not sure if there's another reason why this value doesn't work, but after seeing the note in your README I just thought I'd point it out.

**Comment by tjhrulz** [comment]
Unfortunately this uses the websocket based API for GPMDP as opposed to what some previous methods used which was polling the playback.json file and since the custom theme stuff is currently a feature that is undocumented due to its experimental nature it does not send it when using a custom color.

However I was not aware of this .settings.json file, while querying it will be completely different from everything else and will have to be a pull based method instead of a push  based method it may be worth looking into given that I may be able to automatically adjust user's settings and authenticate myself automatically instead of requiring all skins to include an authentication skin.

**Comment by tjhrulz** [comment]
I have confirmed that custom theme colors are included in the .settings.json, however unlike the default colors they are stored in hex value (Likely why the PlaybackAPI does not support custom colors), if I am able to add support for using the .settings.json file for auto setup I will also add support for this at the same time.

**Comment by tterb** [comment]
That's interesting because after reading your earlier post I double-checked the contents of my .settings.json file and my theme color was in RGB? Could this maybe be a result of changes in some other setting or possibly different versions? I've included a screenshot below for comparison. 
Nevertheless, I understand how querying this would be a completely separate process, which may not be worthwhile for such a minor detail.
 
![2017-04-26_21h54_35](https://cloud.githubusercontent.com/assets/16360374/25468573/a60b14ba-2acb-11e7-925b-fe1a460f32df.png)

**Comment by tjhrulz** [comment]
The theme color seems to be in rgb when using a stock color, but in hex when a custom one (Although maybe it is different if you set it in a certain version). Regardless I have added support for both and read them from that file. Since custom theme colors will be a rare case and since I would have to poll for updates to it I have decided a nice compromise is to just read it during setup of any skin. So in order to get a new custom theme color you will need to refresh the skin. Thanks for reporting this to me.

I am going to leave this issue open to keep the status on auto authenticating the plugin since it is related and both come from the same settings file.

**Comment by tjhrulz** [comment]
Oh the irony, I just rebooted GPMDP and had a new update, seems that they added for custom themes to be sent via the websocket (Although over hex which caused a crash of my plugin)

**Comment by tjhrulz** [comment]
Added support for automatic settings adjustment with version https://github.com/tjhrulz/GPMDP-Plugin/commit/bd7d572dcb3a4a52da168cb766e8b2fe48de47c7

**Comment by tterb** [comment]
Of course, isn't that always the way it goes? haha
Feel free to let me know if there's anything I can help with in the future.
